services:
  - type: web
    name: ketto-care
    env: python
    region: oregon
    plan: free
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
      
      # Install and build frontend
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      sudo apt-get install -y nodejs
      cd frontend
      npm install --legacy-peer-deps
      npm run build
      cd ..
      
      # Verify build
      ls -la frontend/build || echo "Build directory not found"
    startCommand: uvicorn backend.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PORT
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./ketto_care.db