services:
  - type: web
    name: ketto-care
    env: python
    region: oregon
    plan: free
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
      
      # Install Node.js dependencies and build frontend
      cd frontend
      npm install
      npm run build
      cd ..
    startCommand: uvicorn backend.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PORT
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./ketto_care.db